version: "3.4"

networks:
   frontend:
   backend:

services:
  
   eventcatalog:
      build:
         context: .\EventCatalogAPI
         dockerfile: Dockerfile
      image: event/catalogapi
      environment:
         DatabaseServer: mssqlserver
         DatabaseName: eventCatalogdb
         DatabaseUser: sa
         DatabaseUserPassword: ProductApi(!)
      container_name: eventcatalogapi
      ports:
         - "55399:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver

   webmvc:
      build: 
         context: .\WebMvc
         dockerfile: Dockerfile
      environment: 
         ASPNETCORE_ENVIRONMENT: Development 
         EventCatalogUrl: http://eventcatalog
         IdentityUrl: http://localhost:5020
      container_name: webevents
      ports:
         - "5200:80"
      networks:
         - frontend 
      depends_on:
         - eventcatalog
 

   mssqlserver:
      image: "microsoft/mssql-server-linux:latest"
      ports:
         - "1451:1433"

      container_name: mssqlcontainer2
      environment:
         ACCEPT_EULA: Y
         SA_PASSWORD: ProductApi(!)
      networks:
         - backend

