version: "3.4"

networks:
   frontend:
   backend:

services:
   webmvc:
      build: 
         context: .\WebMvc
         dockerfile: Dockerfile
      environment: 
         ASPNETCORE_ENVIRONMENT: Development 
         EventCatalogUrl: http://eventcatalog
         IdentityUrl: http://localhost:5020
      container_name: webevents
      ports:
         - "54143:80"
      networks:
         - frontend 
      depends_on:
         - eventcatalog
 
   eventcatalog:
      build:
         context: .\EventCatalogAPI
         dockerfile: Dockerfile
      image: event/catalogapi
      environment:
         DatabaseServer: mssqlserver
         DatabaseName: eventCatalogdb
         DatabaseUser: sa
         DatabaseUserPassword: ProductApi(!)
      container_name: eventcatalogapi
      ports:
         - "55399:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver

   wishlist:
      build:
         context: .\WishListAPI
         dockerfile: Dockerfile
      image: event/wishlistapi
      environment:
         DatabaseServer: mssqlserver
         DatabaseName: wishlistdb
         DatabaseUser: sa
         DatabaseUserPassword: ProductApi(!)
      container_name: wishlistapi
      ports:
         - "55400:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver
       
   eventticket:
      build:
         context: .\EventTicketAPI
         dockerfile: Dockerfile
      image: event/ticketapi
      environment:
         DatabaseServer: mssqlserver
         DatabaseName: ticketdb
         DatabaseUser: sa
         DatabaseUserPassword: ProductApi(!)
      container_name: eventticketapi
      ports:
         - "55401:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver

   mssqlserver:
      image: "microsoft/mssql-server-linux:latest"
      ports:
         - "1450:1433"
      container_name: mssqlcontainer3
      environment:
         ACCEPT_EULA: Y
         SA_PASSWORD: ProductApi(!)
      networks:
         - backend