version: "3.4"

networks:
   frontend:
   backend:

services:
  
   eventcatalog:
      build:
         context: .\EventCatalogAPI
         dockerfile: Dockerfile
      image: event/catalogapi
      environment:
         DatabaseServer: mssqlserver
         DatabaseName: eventCatalogdb
         DatabaseUser: sa
         DatabaseUserPassword: ProductApi(!)
      container_name: eventcatalogapi
      ports:
         - "55399:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver

   webmvc:
      build: 
         context: .\WebMvc
         dockerfile: Dockerfile
      environment: 
         ASPNETCORE_ENVIRONMENT: Development 
         EventCatalogUrl: http://eventcatalog
         IdentityUrl: http://10.0.75.1:5020
         WishlistUrl: http://wishlist
      container_name: webevents
      ports:
         - "5200:80"
      networks:
         - frontend 
      depends_on:
         - eventcatalog
         - tokenserver
 
   tokenserver:
      build: 
         context: .\TokenServiceAPI
         dockerfile: Dockerfile
      environment: 
         ASPNETCORE_ENVIRONMENT: Development 
         MvcClient: http://localhost:5200
         BasketApiClient: http://localhost:5050
      container_name: tokenserviceapi
      ports:
         - "5020:80"
      networks:
         - backend
         - frontend 
      depends_on:
         - mssqlserver

   mssqlserver:
      image: "microsoft/mssql-server-linux:latest"
      ports:
         - "1450:1433"

      container_name: mssqlcontainer2
      environment:
         ACCEPT_EULA: Y
         SA_PASSWORD: ProductApi(!)
      networks:
         - backend
   wishlist:
      image: wishlistimage
      build:
         context: .\WishListAPI
         dockerfile: Dockerfile
      environment:
         ASPNETCORE_ENVIRONMENT: Development
         IdentityUrl: http://tokenserver
      container_name: wishlistapi
      ports:
         - "5050:80"
      networks:
         - backend
         - frontend
      depends_on:
         - basket.data
         - tokenserver

   basket.data:
      image: redis
      ports:
         - "6377:6379"
      networks:
         - backend


