version: "3.2"

networks:
   frontend:
   backend:

services:
   catalog:
      build:
         context: .\EventCatalogAPI
         dockerfile: Dockerfile
      image: event/eventapi
      environment:
         - DatabaseServer=mssqlserver
         - DatabaseName=eventCatalogdb
         - DatabaseUser=sa
         - DatabaseUserPassword=ProductApi(!)
      container_name: eventcatalogapi
      ports:
         - "55399:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver

   mssqlserver:
      image: "wendyscarlet/mssqlserverevent_template2:ver1.0"
      ports:
         - "1445:1433"

      container_name: mssqlcontainer
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=ProductApi(!)
      networks:
         - backend