version: "3.4"

networks:
   frontend:
   backend:

services:
  
   eventcatalog:
      build:
         context: .\EventCatalogAPI
         dockerfile: Dockerfile
      image: event/catalogapi
      environment:
         DatabaseServer: mssqlserver
         DatabaseName: eventCatalogdb
         DatabaseUser: sa
         DatabaseUserPassword: ProductApi(!)
      container_name: eventcatalogapi3
      ports:
         - "55399:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver

   eventticket:
      build:
         context: .\EventTicketAPI
         dockerfile: Dockerfile
      image: event/ticketapi
      environment:
         DatabaseServer: mssqlserver
         DatabaseName: ticketdb
         DatabaseUser: sa
         DatabaseUserPassword: ProductApi(!)
      container_name: eventticketapi3
      ports:
         - "55401:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver
   webmvc:
      build: 
         context: .\WebMvc
         dockerfile: Dockerfile
      environment: 
         ASPNETCORE_ENVIRONMENT: Development 
         EventCatalogUrl: http://eventcatalog
         IdentityUrl: http://10.0.0.138:5020
         EventTicketUrl: http://eventticket
      container_name: webevents3
      ports:
         - "5200:80"
      networks:
         - frontend 
      depends_on:
         - eventcatalog
         - tokenserver
 
   tokenserver:
      build: 
         context: .\TokenServiceAPI
         dockerfile: Dockerfile
      environment: 
         ASPNETCORE_ENVIRONMENT: Development 
         MvcClient: http://localhost:5200   
      container_name: tokenserviceapi3
      ports:
         - "5020:80"
      networks:
         - backend
         - frontend 
      depends_on:
         - mssqlserver

   mssqlserver:
      image: "microsoft/mssql-server-linux:latest"
      ports:
         - "1450:1433"
      container_name: mssqlserverEvent3
      environment:
         ACCEPT_EULA: Y
         SA_PASSWORD: ProductApi(!)
      networks:
         - backend