version: '3.4'

services:
  eventcatalogapi:
    image: ${DOCKER_REGISTRY}eventcatalogapi
    build:
      context: .
      dockerfile: EventCatalogAPI/Dockerfile

  wishlistapi:
    image: ${DOCKER_REGISTRY}wishlistapi
    build:
      context: .
      dockerfile: ../WishListAPI/Dockerfile


  eventticketapi:
    image: ${DOCKER_REGISTRY}eventticketapi
    build:
      context: .
      dockerfile: ../EventTicketAPI/Dockerfile


  webmvc:
    image: ${DOCKER_REGISTRY}webmvc
    build:
      context: .
      dockerfile: ../WebMvc/Dockerfile

